# -*- coding: utf-8 -*-
"""
/***************************************************************************
 indices
                                 A QGIS plugin
 for calculate indices
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-17
        copyright            : (C) 2019 by sakthi
        email                : sakthivel@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load indices class from file indices.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .indices import indices
    return indices(iface)
